project_name: passbook

before:
  hooks:
    - go mod tidy

builds:
  - id: passbook
    main: ./cmd/passbook
    binary: passbook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    builds:
      - passbook
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{ .Os }}_
      {{ .Arch }}

checksum:
  name_template: checksums.txt

release:
  github:
    owner: mahfuzsust
    name: passbook
  draft: false
  prerelease: auto

brews:
  - name: passbook
    repository:
      owner: mahfuzsust
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/mahfuzsust/passbook"
    description: "PassBook is a terminal-based password vault built in Go."
    license: "MIT"
    test: |
      system "#{bin}/passbook --help"