// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/pb/secret.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VaultParams struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Salt             []byte                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Time             uint32                 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	MemoryKb         uint32                 `protobuf:"varint,4,opt,name=memory_kb,json=memoryKb,proto3" json:"memory_kb,omitempty"`
	Threads          uint32                 `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	Kdf              string                 `protobuf:"bytes,6,opt,name=kdf,proto3" json:"kdf,omitempty"`
	Cipher           string                 `protobuf:"bytes,7,opt,name=cipher,proto3" json:"cipher,omitempty"`
	MasterKeyPurpose string                 `protobuf:"bytes,8,opt,name=master_key_purpose,json=masterKeyPurpose,proto3" json:"master_key_purpose,omitempty"`
	VaultKeyPurpose  string                 `protobuf:"bytes,9,opt,name=vault_key_purpose,json=vaultKeyPurpose,proto3" json:"vault_key_purpose,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VaultParams) Reset() {
	*x = VaultParams{}
	mi := &file_internal_pb_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultParams) ProtoMessage() {}

func (x *VaultParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultParams.ProtoReflect.Descriptor instead.
func (*VaultParams) Descriptor() ([]byte, []int) {
	return file_internal_pb_secret_proto_rawDescGZIP(), []int{0}
}

func (x *VaultParams) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VaultParams) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *VaultParams) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *VaultParams) GetMemoryKb() uint32 {
	if x != nil {
		return x.MemoryKb
	}
	return 0
}

func (x *VaultParams) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *VaultParams) GetKdf() string {
	if x != nil {
		return x.Kdf
	}
	return ""
}

func (x *VaultParams) GetCipher() string {
	if x != nil {
		return x.Cipher
	}
	return ""
}

func (x *VaultParams) GetMasterKeyPurpose() string {
	if x != nil {
		return x.MasterKeyPurpose
	}
	return ""
}

func (x *VaultParams) GetVaultKeyPurpose() string {
	if x != nil {
		return x.VaultKeyPurpose
	}
	return ""
}

type SecretFile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Salt            []byte                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	Time            uint32                 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	MemoryKb        uint32                 `protobuf:"varint,4,opt,name=memory_kb,json=memoryKb,proto3" json:"memory_kb,omitempty"`
	Threads         uint32                 `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	KeyLen          uint32                 `protobuf:"varint,6,opt,name=key_len,json=keyLen,proto3" json:"key_len,omitempty"`
	Kdf             string                 `protobuf:"bytes,7,opt,name=kdf,proto3" json:"kdf,omitempty"`
	VaultParamsHash string                 `protobuf:"bytes,8,opt,name=vault_params_hash,json=vaultParamsHash,proto3" json:"vault_params_hash,omitempty"`
	CommitNonce     []byte                 `protobuf:"bytes,9,opt,name=commit_nonce,json=commitNonce,proto3" json:"commit_nonce,omitempty"`
	CommitTag       string                 `protobuf:"bytes,10,opt,name=commit_tag,json=commitTag,proto3" json:"commit_tag,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	VaultId         string                 `protobuf:"bytes,13,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Reserved01      string                 `protobuf:"bytes,14,opt,name=reserved01,proto3" json:"reserved01,omitempty"`
	PinMode         string                 `protobuf:"bytes,15,opt,name=pin_mode,json=pinMode,proto3" json:"pin_mode,omitempty"`
	PinKey          []byte                 `protobuf:"bytes,16,opt,name=pin_key,json=pinKey,proto3" json:"pin_key,omitempty"`
	PinVerifyTag    string                 `protobuf:"bytes,17,opt,name=pin_verify_tag,json=pinVerifyTag,proto3" json:"pin_verify_tag,omitempty"`
	TotpSecret      string                 `protobuf:"bytes,18,opt,name=totp_secret,json=totpSecret,proto3" json:"totp_secret,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecretFile) Reset() {
	*x = SecretFile{}
	mi := &file_internal_pb_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretFile) ProtoMessage() {}

func (x *SecretFile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretFile.ProtoReflect.Descriptor instead.
func (*SecretFile) Descriptor() ([]byte, []int) {
	return file_internal_pb_secret_proto_rawDescGZIP(), []int{1}
}

func (x *SecretFile) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretFile) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *SecretFile) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SecretFile) GetMemoryKb() uint32 {
	if x != nil {
		return x.MemoryKb
	}
	return 0
}

func (x *SecretFile) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *SecretFile) GetKeyLen() uint32 {
	if x != nil {
		return x.KeyLen
	}
	return 0
}

func (x *SecretFile) GetKdf() string {
	if x != nil {
		return x.Kdf
	}
	return ""
}

func (x *SecretFile) GetVaultParamsHash() string {
	if x != nil {
		return x.VaultParamsHash
	}
	return ""
}

func (x *SecretFile) GetCommitNonce() []byte {
	if x != nil {
		return x.CommitNonce
	}
	return nil
}

func (x *SecretFile) GetCommitTag() string {
	if x != nil {
		return x.CommitTag
	}
	return ""
}

func (x *SecretFile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SecretFile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SecretFile) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *SecretFile) GetReserved01() string {
	if x != nil {
		return x.Reserved01
	}
	return ""
}

func (x *SecretFile) GetPinMode() string {
	if x != nil {
		return x.PinMode
	}
	return ""
}

func (x *SecretFile) GetPinKey() []byte {
	if x != nil {
		return x.PinKey
	}
	return nil
}

func (x *SecretFile) GetPinVerifyTag() string {
	if x != nil {
		return x.PinVerifyTag
	}
	return ""
}

func (x *SecretFile) GetTotpSecret() string {
	if x != nil {
		return x.TotpSecret
	}
	return ""
}

var File_internal_pb_secret_proto protoreflect.FileDescriptor

const file_internal_pb_secret_proto_rawDesc = "" +
	"\n" +
	"\x18internal/pb/secret.proto\"\x8a\x02\n" +
	"\vVaultParams\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\x12\x12\n" +
	"\x04time\x18\x03 \x01(\rR\x04time\x12\x1b\n" +
	"\tmemory_kb\x18\x04 \x01(\rR\bmemoryKb\x12\x18\n" +
	"\athreads\x18\x05 \x01(\rR\athreads\x12\x10\n" +
	"\x03kdf\x18\x06 \x01(\tR\x03kdf\x12\x16\n" +
	"\x06cipher\x18\a \x01(\tR\x06cipher\x12,\n" +
	"\x12master_key_purpose\x18\b \x01(\tR\x10masterKeyPurpose\x12*\n" +
	"\x11vault_key_purpose\x18\t \x01(\tR\x0fvaultKeyPurpose\"\x92\x04\n" +
	"\n" +
	"SecretFile\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\x12\x12\n" +
	"\x04time\x18\x03 \x01(\rR\x04time\x12\x1b\n" +
	"\tmemory_kb\x18\x04 \x01(\rR\bmemoryKb\x12\x18\n" +
	"\athreads\x18\x05 \x01(\rR\athreads\x12\x17\n" +
	"\akey_len\x18\x06 \x01(\rR\x06keyLen\x12\x10\n" +
	"\x03kdf\x18\a \x01(\tR\x03kdf\x12*\n" +
	"\x11vault_params_hash\x18\b \x01(\tR\x0fvaultParamsHash\x12!\n" +
	"\fcommit_nonce\x18\t \x01(\fR\vcommitNonce\x12\x1d\n" +
	"\n" +
	"commit_tag\x18\n" +
	" \x01(\tR\tcommitTag\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12\x19\n" +
	"\bvault_id\x18\r \x01(\tR\avaultId\x12\x1e\n" +
	"\n" +
	"reserved01\x18\x0e \x01(\tR\n" +
	"reserved01\x12\x19\n" +
	"\bpin_mode\x18\x0f \x01(\tR\apinMode\x12\x17\n" +
	"\apin_key\x18\x10 \x01(\fR\x06pinKey\x12$\n" +
	"\x0epin_verify_tag\x18\x11 \x01(\tR\fpinVerifyTag\x12\x1f\n" +
	"\vtotp_secret\x18\x12 \x01(\tR\n" +
	"totpSecretB\x19Z\x17passbook/internal/pb;pbb\x06proto3"

var (
	file_internal_pb_secret_proto_rawDescOnce sync.Once
	file_internal_pb_secret_proto_rawDescData []byte
)

func file_internal_pb_secret_proto_rawDescGZIP() []byte {
	file_internal_pb_secret_proto_rawDescOnce.Do(func() {
		file_internal_pb_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_secret_proto_rawDesc), len(file_internal_pb_secret_proto_rawDesc)))
	})
	return file_internal_pb_secret_proto_rawDescData
}

var file_internal_pb_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_pb_secret_proto_goTypes = []any{
	(*VaultParams)(nil), // 0: VaultParams
	(*SecretFile)(nil),  // 1: SecretFile
}
var file_internal_pb_secret_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_secret_proto_init() }
func file_internal_pb_secret_proto_init() {
	if File_internal_pb_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_secret_proto_rawDesc), len(file_internal_pb_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_secret_proto_goTypes,
		DependencyIndexes: file_internal_pb_secret_proto_depIdxs,
		MessageInfos:      file_internal_pb_secret_proto_msgTypes,
	}.Build()
	File_internal_pb_secret_proto = out.File
	file_internal_pb_secret_proto_goTypes = nil
	file_internal_pb_secret_proto_depIdxs = nil
}
